# 热部署
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#  profiles:
#    active: local


#logging:
#  config: classpath:config/logback.xml
server:
  port: 8081


